export { Forum } from "./Forum";
export { Account } from "./Account";
export { Settings } from "./Settings";
export { Discover } from "./Discover";
export { Home } from "./Home";
// export { Topup } from "./Topup";
export { Receipt } from "./Receipt";
export { Comments } from "./Comments";
export { Login } from "./Login";
export { Register } from "./Register";
